on:
  push:
    branches:
      - master
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: maven
          package-name: TitansBattle
          token: ${{ secrets.PAT_TOKEN }}

      - name: Checkout code
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4

      - name: Set up JDK 21
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "maven"

      - name: Build with Maven
        if: ${{ steps.release.outputs.release_created }}
        run: |
          mvn clean package -DskipTests
          rm -f target/original-*.jar

      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          JAR_FILE=$(find target -name "*.jar" | head -n 1)
          gh release upload ${{ steps.release.outputs.tag_name }} "$JAR_FILE"
